// Settings:
:toc: macro
:numbered: 1
:sectids: 1
:sectlinks: 1

= nocloud

toc::[]

<<<
:numbered:

<<<

== TL;DR

nocloud is a set of tools to run a mini-cloud on your machine based on kvm / qemu and written in bash.

To install, get a template and instanciate 5 times this template :

 sudo make
 vmtemplate -d debian8
 vmrun -g test -m debian8:5:deb

== Presentation

nocloud is a cheap solution to own your cloud. It was first developped as a side project to provide the tools I needed for my virtualbox usage. I switched to kvm backend but keeping in mind the possibility to offer multiple backends.

it is :

- modular (composed of multiple simple and one-task-only command-line tools)
- using kvm to manage vms
- using ansible to configure vms

it is not :

- ment to be a production cloud platform
- bug free

I therefore only have tested with Archlinux hosts and it has been reported to me to run on ubuntu. Debian, Centos and Archlinux guests were tested. And this is what will be use next as examples. Examples will be simple. Multiple options are available and are documented through the -h option of each script.

== System pre-requisites

Following things needs to be installed on your machine :

- qemu
- dnsmasq
- make
- tree

Note that for users to use kvm and nocloud, you must add them to the kvm group :

  useradd -a -G kvm my_user

== Network

=== Configuration

The solution is based on bridging capability. Setup needs root access and I want to reduce sudo commands through the tools at its minimum. Needs are explained below.

During installation, 2 services are created :

- nocloud-bridge which creates a bridge interface and sets up firewalling rules
- nocloud-dnsmasq brings a dnsmasq server up to serve DHCP and DNS to the machines

The configuration file /etc/qemu/bridge.conf is also created during installation. It allows qemu to bring machines interfaces connected to the bridge inteface.

Installation also configures the kvm_intel and vhost_net modules.

Note : if you restart your iptables, the nocloud rules will be dropped. no-cloud-bridge service needs to be restarted as well.

== Installation

Only thing to do is :

 sudo make

== Cloud initialization and template managment

Everything starts with a template.

You first need to have an ISO of the system you want to install (ex: archlinux.iso). You then create a VM using this ISO :

 vmtemplate -c archlinux -i archlinux.iso

Once the machine created, it will start and you will have to make your template corresponding to the following standards :

- VM must be accessible through ssh (ssh service enabled and configured on 22 port)
- ssh key (found in /usr/local/etc/nocloud.pub) must be added to /root/.ssh/authorized_keys
- network is using dhcp (dhcp service is enabled)
- python is better to be installed has ansible is the tool of choice to operate on those VMs

You can create as much templates as you want.

== Template downloading

You can download existing templates using this :

 vmtemplate -d archlinux

available templates can be listed with -h option

== Clone generation

=== Manual

Once your template is good, you can use it to generate new VMs :

 vmrun -r test -m archlinux:2:arch

will create two new machines, fresh copies from of the template. Those machines will have generated names and the template's disk is set to read-only before creating the clones. The clones will run without graphical interface.

In order to organize your VMs they are grouped. This is done using a two level hierarchy :

- groups will represent a kind of platform, a set of machines you use for a service.
- types will be subgroups of servers that will group VMs by function.

For instance, you run your application named ''awesome'' constituted of a database serveur and two web servers. You would create the set with this line :

 vmrun -r awesome -m archlinux:2:web -m debian8:1:sql

Precision on VM specifications is given below.

=== Using description file

If you want to automate the creation of a set of VMs, you can create description files. Each line matches a vminstantiate command line parameters. Those are separated by ":" and are in the following order :

- template name
- number of clones
- type name

The group of machines will be deduced from the file name.

For instance the following file produces 2 VMs of type web and 1 VM of type sql :

 archlinux:1:sql
 archlinux:2:web

You can specify cpu and memory for each line using the following syntax :

 archlinux:1:sql:mem=1024;cpu=4
 archlinux:2:web:mem=512

You can also add additional disks for VMs with the dsk option (sizes in GB) :

 archlinux:1:sql:mem=1024;cpu=4;dsk=5,5
 archlinux:2:web:mem=512

If you want your machines to have more human-friendly names (instead of UUIDs), specify a name prefix :

 archlinux:1:sql:mem=1024;cpu=4;name=db
 archlinux:2:web:mem=512;name=web

This will create a server called db00 for the first line and two servers on the second, called web00 and web01.

The file (named pftest) is called with the following command :

 vmrun -f pftest

And so the machines will be in the pftest group.

Groups and types, besides being structural in the VM directory structure, and for naming purpose, will be used for instance if you configure those machines with ansible. Once the previous instanciation has been done, you can use dynamic inventory :

 vminventory --list
 {
   "pftest_sql" : {
     "hosts" : [  "192.168.1.176", ],
   },
   "pftest_web" : {
     "hosts" : [  "192.168.1.19", "192.168.1.23", ],
   },
   "pftest" : {
     "children" : [ "pftest_sql", "pftest_web", ],
     "vars": {
       "ansible_ssh_common_args": "-o StrictHostKeyChecking=no",
       "ansible_user": "root",
     },
   },
 }

You can then stop your VMs using (-d option destroys the machines) :

 vmmanage -s -g pftest -d

Alternatively, you can launch your description file using :

 vmrun -f pftest

It will stay in foreground and log (hopefuly) useful information until you press ^C which will make it kill and destroy all its machines.

== A beautiful picture

[source]
----





    internet --------
        |           |
        |           v
        |        __________        ___________
        v       /          \      |           |
       iso --> | vmtemplate | --> | TEMPLATES |
                \__________/      |___________|      _______
                                        |           |$>     |
                                        |           |       |
                    _____               |           |_______|
                   /     \              |          /         \
                  | vmrun | <------------         /___________\
                   \____ /                            |
                      |        ________               v
                      |      _|______  |           _____
                      |    _|______  | |          /     \
          ________    --> |        | |_| <------ | vmssh |
         /        \       |   VM   |_|            \____ /
        | vmmanage | ---> |________|
         \________/            |
                               v                            _______
                          __________                       |      |\
                         /           \                     |   VM |_\
                        | vminventory | -----------------> |  list   |
                         \___________/                     |         |
                                                           | - vm1   |
                                                           | - vm2   |
                          vminventory                      |_________|

----

== Tools


=== vmtemplate - templates creation and downloading

vmtemplate manages templates. It has two main functions : creating templates and downloading templates.

You can download templates using the following form :

----
vmtemplate -d TEMPLATE_NAME
----

Available templates are displayed by the -h option :

----
vmtemplate -h
----

You can create your own template with :

----
vmtemplate -c TEMPLATE_NAME -i ISO_NAME
----

* ISO_NAME is either the name of a template in configured iso directory, or a path to a file.
* TEMPLATE_NAME must not be the name of an existing template.

You can get the templates list with :

----
vmtemplate -L
----

=== vmrun - run all the VMs of a group

vmrun launches VMs from templates, using spec files or inline specifications. It can also rerun an existing group.

To run from a spec file :

----
vmrun -f my_group
----

to run directly from the command line :

----
vmrun -r my_group -m debian8:2:web -m debian8:1:sql
----

More complete description of VM specifications can be found above in this documentation.

=== vminventory - list all the running guests on the host

vminventory is used to list running and existing VMs.

To get running VMs :

----
vminventory
----

To get existing (but not only running) groups and types :

----
vminventory -L
----

vminventory also provides an ansible dynamic inventory, using the --list option. You can then call ansible or ansible-playbook using the script as inventory :

----
ln -s /usr/local/bin/vminventory inventory
ansible-playbook -i inventory playbook.yml
----

=== vmmanage - managing running VMs

vmmanage deals with running VMs and groups maintainance. It can connect :

* to qemu console (vmmanage -m tst00)
* to the VM console (vmmanage -c tst00)

It can also launch a template :

----
vmmanage -T archlinux
----

Last usage is that it can stop a running group, and optionnaly destroy all of its VMs.

----
vmmanage -s -g my_group
----

=== vmssh - connect to VMs

vmssh connects you to a VM usgin ssh. You can name VM by its name or IP address. It also can take a command as argument, as ssh does.

----
vmssh 192.168.1.12 hostname
vmssh tst00
----

=== vmupgrade - OS upgrade

vmupgrade runs a system upgrade on a template if it knows how. It currently knows how to upgrade archlinux, debian and ubuntu systems.

----
vmupgrade debian8
----
