#!/usr/bin/env bash

usage() {
  echo "$@" >&2
  echo "usage : $(basename $0) [options]
  -g <GROUP> : restrict selection to this group
  -t <TYPE> : restrict selection to this type
  -h : display this help" >&2
  exit
}

realMe=$(readlink -e $0)
realDir=$(dirname ${realMe})
libDir=lib
libName=cm_lib
[ -d "${realDir}/${libDir}" ]  || usage "${libDir} directory was not found in ${realDir} : Installation problem."
[ -f "${realDir}/${libDir}/${libName}" ] && . ${realDir}/${libDir}/${libName} || usage "${libName} was not found in ${realDir}/${libDir} : Installation problem."

groupName="*"
subGroupName="*"
while getopts g:t:h name
do
  case $name in
    g) groupName="$OPTARG" ;;
    t) subGroupName="$OPTARG" ;;
    h) usage ;;
  esac
done
shift $(($OPTIND-1))

vm_running "${groupName}" "${subGroupName}"
