#!/usr/bin/env bash

#    (c) 2016-2017, n0vember <n0vember@half-9.net>
#
#    This file is part of nocloud.
#
#    nocloud is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    nocloud is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with nocloud.  If not, see <http://www.gnu.org/licenses/>.

# Following variables are default values. They can be redefined in .nocloud.conf, ~/.config/nocloud/nocloud.conf or /etc/nocloud.conf

noCloudVersion=1.3

vmMem=512
vmMemVid=12
vmCpu=2
vmCpuCap=50
vmCreateGroup="templates"
vmCreateDiskSize=10
vmSpicePassword="nocloud"

vmCount=1
vmDefaultGroup="group"
vmDefaultSubGroup="default"
vmGroup=${vmDefaultGroup}
vmSubGroup=${vmDefaultSubGroup}

isoDir="$HOME/Documents/distribs/linux"

bridgeInterface=bridge0
bridgeAddress=192.168.1.1/24
bridgeNet=192.168.1.0/24
bridgeDhcpStart=192.168.1.2
bridgeDhcpStop=192.168.1.254

[ -z ${realDir} ] && realDir=$(dirname $0)
[ -z ${libDir} ] && libDir=../lib
[ -z ${etcDir} ] && etcDir=../etc

netConf=${realDir}/${etcDir}/nocloud_net.conf
[ -f ${netConf} ] && . ${netConf}

# for now, can be : kvm (virtualbox planned)
vmBackend=kvm
. ${realDir}/${libDir}/${vmBackend}_lib

# Common functions

version() {
  echo "nocloud ${noCloudVersion}"
  exit
}

nonNumeric() {
  noNum=$(echo "$@" | sed "s/[^0-9]//g")
  [ "$noNum " != "$@ " ] && echo 1 || echo 0
}

log() {
  echo "$(date "+%Y/%m/%d %H:%M:%S.%N") $@"
}

log_error() {
  echo "$(date "+%Y/%m/%d %H:%M:%S.%N") $@" >&2
}

error() {
  echo "$@" >&2
  exit 1
}

free_port() {
  local portOffset=$1
  [ -z "${portOffset}" ] && portOffset=1
  portOffset=$((portOffset+1))

  seq 1024 65535 | grep -v -f <(netstat -tlna | tr -s " " " " | cut -d " " -f 4 | cut -d : -f 2 | grep -E "^[0-9]+$" | sort -n) | tail -${portOffset} | head -1
}

cm_check() {
  local bridgeInterface=$1

  # Testing pre-requisites
  [ -d /etc/qemu ] || error "/etc/qemu does not exist. Please read documentation."
  [ -f /etc/qemu/bridge.conf ] || "/etc/qemu/bridge.conf does not exist. Please read documentation."
  grep "^allow " /etc/qemu/bridge.conf >/dev/null 2>&1 || error "no bridging allowed for qemu. Please read documentation."

  local bridgeInterfaceUp=$(ip link | sed -r '/^[0-9]+:/!d;s/[0-9]+: ([^:]+):.*/\1/' | grep -c "^${bridgeInterface}$")
  [ ${bridgeInterfaceUp} -eq 0 ] && error "${bridgeInterface} bridge interface is not available. Please read documentation."
}

cm_check ${bridgeInterface}

# ConfFile search and source
confFile=~/.nocloud.conf
[ -f ${confFile} ] || confFile=~/.config/nocloud/nocloud.conf
[ -f ${confFile} ] || confFile=/etc/nocloud.conf
if [ -f ${confFile} ] ; then
  . ${confFile}
fi
