#!/usr/bin/env bash

vmBaseDir="$HOME/Documents/kvm/VMs"
vmDiskExt="img"
vmSystemType=x86_64

vm_disk_create() {
  vmName=$1
  vmCreateGroup=$2
  vmCreateDiskSize=$3

  vmDisk=${vmBaseDir}/${vmCreateGroup}/${vmName}/${vmName}.${vmDiskExt}
  if [ -f ${vmDisk} ]
  then
    echo ${vmDisk}
  else
    vmDiskPath=$(dirname ${vmDisk})
    mkdir -p $vmDiskPath || usage "unable to create ${vmDiskPath}"
    qemu-img create -f raw ${vmDisk} ${vmCreateDiskSize}G >/dev/null >&2
    ret=$?

    [ $ret -eq 0 ] && echo ${vmDisk} || usage "unable to create ${vmDisk}"
  fi
}

vm_run() {
  vmName=$1
  vmGroup=$2
  isoName=$3
  guiOpt=$4

  isoOpt="-cdrom ${isoDir}/${isoName}"
  [ "${isoName} " == "none " ] && isoOpt=""

  vmNoGui="-sdl" # -no-quit
  [ "${guiOpt} " == "gui " ] || vmNoGui="--display none"

  [ -f ${vmBaseDir}/${vmCreateGroup}/${vmName}/${vmName}.conf ] && . ${vmBaseDir}/${vmCreateGroup}/${vmName}/${vmName}.conf

  qemu-system-${vmSystemType} \
    -enable-kvm \
    ${isoOpt} \
    -boot order=d \
    -drive file="${vmDisk}",format=raw \
    -smp cpus=1,cores=${vmCpu},maxcpus=${vmCpu} \
    -m ${vmMem} \
    -name ${vmName} \
    -D ${vmBaseDir}/${vmGroup}/${vmName}/${vmName}.log \
    --daemonize \
    ${vmNoGui} \
    #>/dev/null 2>&1
}

vm_create() {
  vmName=$1
  vmCreateGroup=$2
  isoName=$3

  vmDisk=${vmBaseDir}/${vmCreateGroup}/${vmName}/${vmName}.${vmDiskExt}
  [ -f ${vmDisk} ] || ${vmDisk}=$(vm_disk_create ${vmName} ${vmCreateGroup} ${vmCreateDiskSize})
  vm_run ${vmName} ${vmCreateGroup} ${isoName} gui
}
