#!/usr/bin/env bash

#    (c) 2016-2017, n0vember <n0vember@half-9.net>
#
#    This file is part of nocloud.
#
#    nocloud is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    nocloud is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with nocloud.  If not, see <http://www.gnu.org/licenses/>.

# This is kvm implementation of the nocloud lib

vmBaseDir="$HOME/Documents/kvm/VMs"
vmDiskExt="img"
vmSystemType=$(uname -m)

vmTemplates="archlinux debian8 centos7 debian9"
vmTemplatesDetails="
archlinux;http://n0vember.free.fr/nocloud/templates/archlinux;07bd89e3244b92a27abc7485d56e46b8;15
debian8;http://n0vember.free.fr/nocloud/templates/debian8;18355f4ce9673be5523f831f062eea28;19
centos7;http://n0vember.free.fr/nocloud/templates/centos7;0ead1ad701408f5da7dceb48624adf8f;12
debian9;http://n0vember.free.fr/nocloud/templates/debian9;23d0ed780c6ff5d0210d97384153f856;14
"

vm_disk_create() {
  local vmName=$1
  local vmCreateGroup=$2
  local vmCreateType=$3
  local vmCreateDiskSize=$4

  [ -n "${vmCreateType}" ] && vmCreateGroup=${vmCreateGroup}/${vmCreateType}
  local vmDiskCount=0
  while [ -f "${vmBaseDir}/${vmCreateGroup}/${vmName}/${vmName}_${vmDiskCount}.${vmDiskExt}" ] ; do vmDiskCount=$((vmDiskCount+1)) ; done
  local vmDisk="${vmCreateGroup}/${vmName}/${vmName}_${vmDiskCount}.${vmDiskExt}"
  if [ -f "${vmBaseDir}/${vmDisk}" ]
  then
    echo "${vmBaseDir}/${vmDisk}"
  else
    local vmDiskPath=$(dirname "${vmBaseDir}/${vmDisk}")
    mkdir -p "$vmDiskPath" || usage "unable to create ${vmDiskPath}"
    qemu-img create -q -f qcow2 "${vmBaseDir}/${vmDisk}" ${vmCreateDiskSize}G >/dev/null >&2
    ret=$?
    [ $ret -eq 0 ] && echo "${vmDisk}" || usage "unable to create ${vmBaseDir}/${vmDisk}"
  fi
}

vm_stop() {
  local vmName=$1
  local vmGroup=$2
  local vmSubGroup=$3

  vmDir="${vmBaseDir}/${vmGroup}/${vmSubGroup}/${vmName}/"
  [ -z "${vmSubGroup}" ] && vmDir="${vmBaseDir}/${vmGroup}/${vmName}/"
  vmDir=$(echo "${vmDir}" | sed 's://:/:g')
  pgrep -f qemu-system-${vmSystemType} -a | grep "file=${vmDir}" | cut -d " " -f 1 | xargs kill
}

vm_run() {
  local vmName=$1
  local vmGroup=$2
  local vmSubGroup=$3
  local isoName=$4
  local guiOpt=$5

  local isoOpt=""
  [ -f "${isoDir}/${isoName}" ] && isoOpt="-cdrom ${isoDir}/${isoName}"
  [ -f "${isoName}" ] && isoOpt="-cdrom ${isoName}"
  [ "${isoName} " == "none " ] && isoOpt=""

  local vmNoGui="-display sdl -vga virtio -no-quit"
  [ "${guiOpt} " == "gui " ] || vmNoGui="--display none"

  local spicePort=$(free_port 1)
  local telnetPort=$(free_port 2)
  local vmMonitor="-monitor telnet:127.0.0.1:${telnetPort},server,nowait"
  local vmSpice="-spice port=${spicePort},addr=localhost,password=${vmSpicePassword}"

  local memOpt=""
  local hugePageSize=$(grep "^Hugepagesize:" /proc/meminfo | tr -s " " " " | cut -d " " -f 2)
  local hugePageFree=$(grep "^HugePages_Free:" /proc/meminfo | tr -s " " " " | cut -d " " -f 2)
  hugePageFree=$((hugePageFree*hugePageSize/1024))

  local maxCpu=$(LC_ALL=C lscpu | grep ^CPU\(s\) | tr -s " " " " | cut -d " " -f 2)
  local cpuType="host"
  #local cpuType="qemu64,+vmx"

  [ -f "${vmBaseDir}/${vmGroup}/${vmSubGroup}/${vmName}/${vmName}.conf" ] && . "${vmBaseDir}/${vmGroup}/${vmSubGroup}/${vmName}/${vmName}.conf"
  [ ${vmMem} -le ${hugePageFree} ] && memOpt="-mem-path /dev/hugepages"

  [ -n "${vmExtraDisk}" ] && vmExtraDisk=$(
    echo "${vmExtraDisk}" | \
    sed -r 's/^/</;s/$/>/;s/,/> </g' |
    sed "s:<:-drive file=${vmBaseDir}/:g" | \
    sed 's/>/,format=qcow2,if=virtio/g' \
  )

  vmMac=$(vm_mac_gen ${vmName})
  qemu-system-${vmSystemType} \
    -enable-kvm \
    ${isoOpt} \
    ${memOpt} \
    -boot order=d \
    -drive file="${vmBaseDir}/${vmDisk}",format=qcow2,if=virtio ${vmExtraDisk} \
    -cpu ${cpuType} \
    -smp cpus=${vmCpu},cores=1,maxcpus=${maxCpu} \
    -m ${vmMem} \
    -name ${vmName} \
    -D "${vmBaseDir}/${vmGroup}/${vmSubGroup}/${vmName}/${vmName}.log" \
    --daemonize \
    ${vmNoGui} ${vmMonitor} ${vmSpice} \
    -net nic,model=virtio,macaddr=${vmMac} -net bridge,br=${bridgeInterface}
    >/dev/null 2>&1
}

vm_mac_gen() {
  echo $(uuidgen) | sed -r 's/-//g;s/^(.{6}).*/005056\1/;s/(..)/\1:/g;s/:$//'
}

vm_get_mac() {
  local vmName=$1

  pgrep -f qemu-system-${vmSystemType} -a | grep " .name ${vmName}" | sed 's/.*macaddr=//;s/ .*$//'
}

vm_create() {
  local vmName=$1
  local vmGroup=$2
  local vmType=$3
  local isoName=$4
  local guiNoGui=$5

  local gui="gui"

  [ -f ${vmBaseDir}/${vmGroup}/${vmType}/${vmName} ] || mkdir -p ${vmBaseDir}/${vmGroup}/${vmType}/${vmName}
  vmDisk="$(vm_disk_create ${vmName} ${vmGroup} "${vmType}" ${vmCreateDiskSize})"
  cat > ${vmBaseDir}/${vmGroup}/${vmType}/${vmName}/${vmName}.conf <<EOF
vmName=${vmName}
vmMem=${vmMem}
vmCpu=${vmCpu}
vmDisk=${vmDisk}
EOF
  [ "${guiNoGui}" == "no" ] && gui=""
  vm_run ${vmName} ${vmGroup} "${vmType}" "${isoName}" ${gui}
}

vm_clone_disk() {
  local vmSrcGroup=$1
  local vmSrcType=$2
  local vmSrc=$3
  local vmDestGroup=$4
  local vmDestType=$5
  local vmDest=$6

  local vmSrcDir="${vmBaseDir}/${vmSrcGroup}/${vmSrcType}/${vmSrc}"
  [ -z "${vmSrcType}" ] && vmSrcDir="${vmBaseDir}/${vmSrcGroup}/${vmSrc}"
  local vmSrcCount=$(ps -A -o args | grep qemu-system-${vmSystemType} | grep -v grep | grep "${vmSrcDir}/" | wc -l)
  [ ${vmSrcCount} -ne 0 ] && usage "can't clone a running vm"
  . ${vmSrcDir}/${vmSrc}.conf
  [ -f "${vmBaseDir}/${vmDisk}" ] || usage "can't clone non-existing disk ${vmSrcDisk}"
  chmod a-w "${vmBaseDir}/${vmDisk}"
  local vmDestDir="${vmDestGroup}/${vmDestType}/${vmDest}"
  local vmDestDiskCount=0
  while [ -f "${vmBaseDir}/${vmDestDir}/${vmDest}_${vmDestDiskCount}.${vmDiskExt}" ] ; do vmDestDiskCount=$((vmDestDiskCount+1)) ; done
  local vmDestDisk="${vmDestDir}/${vmDest}_${vmDestDiskCount}.${vmDiskExt}"
  mkdir -p "${vmBaseDir}/${vmDestDir}" || usage "unable to create ${vmBaseDir}/${vmDestDir}"
  qemu-img create -q -f qcow2 -b "${vmBaseDir}/${vmDisk}" "${vmBaseDir}/${vmDestDisk}" >/dev/null >&2
  echo "${vmDestDisk}"
}

vm_running() {
  local groupName="$1"
  local subGroupName="$2"

  [ "${groupName}" == "*" ] && groupName='[^/]*'
  [ "${subGroupName}" == "*" ] && subGroupName='[^/]*'
  subGroupDir="${vmBaseDir}/${groupName}/${subGroupName}"
  [ "${groupName}" == "${vmCreateGroup}" ] && subGroupDir="${vmBaseDir}/${groupName}"

  for vmPath in $(pgrep -f qemu-system-${vmSystemType} -a | grep "file=${subGroupDir}/" | sed -r "s:^.* file\=${vmBaseDir}/::;s:/[^/]+,.*::")
  do
    vmName=$(echo ${vmPath} | sed -r 's:.*/([^/]+)$:\1:')
    vmGroup=$(echo ${vmPath} | sed -r "s:/${vmName}::")
    vmMac=$(vm_get_mac ${vmName})
    vmIP=$(grep " ${vmMac} " /var/lib/misc/dnsmasq.leases | cut -d " " -f 3)
    echo ${vmName} ${vmGroup} ${vmIP}
  done
}

vm_configure() {
  local vmName=$1

  local vmIp=$(vm_ip ${vmName})
  vm_ssh ${vmIp} "echo ${vmName} > /etc/hostname ; hostname -F /etc/hostname"
}

vm_instantiate() {
  local vmTemplate=$1
  local vmCount=$2
  local vmGroup=$3
  local vmSubGroup=$4
  local vmOpts=$5

  [ -z ${vmGroup} ] && vmGroup=${vmDefaultGroup}
  [ -z ${vmSubGroup} ] && vmSubGroup=${vmDefaultSubGroup}

  local memOpt=${tmplt_vmMem}
  local cpuOpt=${tmplt_vmCpu}
  local dskOpt=
  local dskList=
  local guiOpt=
  if [ -n "${vmOpts}" ] ; then
    for vmOpt in ${vmOpts}
    do
      echo ${vmOpt} | grep ^name= >/dev/null 2>&1 && nameOpt=$(echo $vmOpt | sed 's/^name=//')
      echo ${vmOpt} | grep ^mem= >/dev/null 2>&1 && memOpt=$(echo $vmOpt | sed 's/^mem=//')
      echo ${vmOpt} | grep ^cpu= >/dev/null 2>&1 && cpuOpt=$(echo $vmOpt | sed 's/^cpu=//')
      echo ${vmOpt} | grep ^dsk= >/dev/null 2>&1 && dskOpt=$(echo $vmOpt | sed 's/^dsk=//')
      echo ${vmOpt} | grep ^gui  >/dev/null 2>&1 && guiOpt="gui"
    done
  fi

  local vmTemplateGroup=${vmCreateGroup}
  . <(sed 's/^/tmplt_/' ${vmBaseDir}/${vmTemplateGroup}/${vmTemplate}/${vmTemplate}.conf)

  local vmList=
  local vmDir=${vmBaseDir}/${vmGroup}/${vmSubGroup}
  local vmIdx=0
  for vmNum in $(seq 1 ${vmCount})
  do
    local vmName=$(uuidgen)
    [ ${vmIdx} -lt 10 ] && vmIdx="0${vmIdx}"
    [ -n "${nameOpt}" ] && vmName=${nameOpt}${vmIdx}
    [ -f ${vmDir}/${vmName} ] || mkdir -p ${vmDir}/${vmName}
    local vmDisk=$(vm_clone_disk ${vmTemplateGroup} "" ${vmTemplate} ${vmGroup} ${vmSubGroup} ${vmName})
    [ -z ${memOpt} ] && memOpt=${tmplt_vmMem}
    [ -z ${cpuOpt} ] && cpuOpt=${tmplt_vmCpu}
    if [ -n "${dskOpt}" ] ; then
      for dskSize in $(echo ${dskOpt} | tr ',' ' ')
      do
        dskName=$(vm_disk_create ${vmName} ${vmGroup} ${vmSubGroup} ${dskSize})
        [ -z "${dskList}" ] && dskList="${dskName}" || dskList="${dskList},${dskName}"
      done
    fi
    cat > ${vmDir}/${vmName}/${vmName}.conf <<EOF
vmName=${vmName}
vmMem=${memOpt}
vmCpu=${cpuOpt}
vmDisk=${vmDisk}
vmExtraDisk=${dskList}
EOF
    vm_run ${vmName} ${vmGroup} ${vmSubGroup} none ${guiOpt}
    vmList="${vmList} ${vmName}"
    vmIdx=$((vmIdx+1))
  done

  for vmName in ${vmList}
  do
    vm_configure ${vmName} >/dev/null 2>&1 &
  done

  #wait

  for vmName in $vmList
  do
    echo ${vmName}
  done
}

is_vm_running() {
  local vmName=$1
  local vmGroup=$2
  local vmSubGroup=$3

  [ -z "${vmGroup}" ] && vmGroup="*"
  [ -z "${vmSubGroup}" ] && vmSubGroup="*"
  local vmIsRunning=$(vm_running "${vmGroup}" "${vmSubGroup}" | grep "^${vmName} " | wc -l)
  echo ${vmIsRunning}
  [ ${vmIsRunning} -eq 1 ] && return 0 || return 1
}

vm_ssh() {
  local vmIp=$1
  local vmIpTest=$(echo "${vmIp}" | sed -r '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/!d')
  [ "${vmIpTest}" != "${vmIp}" ] && vmIp=$(vm_ip ${vmIp})
  shift

  grep "^${vmIp}[ ,]" ~/.ssh/known_hosts >/dev/null && ssh-keygen -R ${vmIp} >/dev/null
  sshTry=0
  sshTryMax=30
  while [ ${sshTry} -le ${sshTryMax} ]
  do
    ssh -o StrictHostKeyChecking=false root@${vmIp} true >/dev/null 2>&1 && break
    sleep 1
    sshTry=$((${sshTry}+1))
  done
  [ ${sshTry} -gt ${sshTryMax} ] && return 1
  ssh -o StrictHostKeyChecking=false root@${vmIp} "$@"
}

vm_ip() {
  local vmName=$1

  vmIp=
  ipFindingIteration=0
  ipFindingIterationMax=30
  while [ ${ipFindingIteration} -le ${ipFindingIterationMax} ]
  do
    vmIp=$(vm_running "*" "*" | grep ^${vmName} | cut -d ' ' -f 3)
    [ -n "${vmIp}" ] && break
    sleep 1
    ipFindingIteration=$((${ipFindingIteration}+1))
  done
  [ ${ipFindingIteration} -gt ${ipFindingIterationMax} ] && return 1
  echo $vmIp
}

vm_name() {
  local vmIp=$1

  vmName=
  nameFindingIteration=0
  nameFindingIterationMax=30
  while [ ${nameFindingIteration} -le ${nameFindingIterationMax} ]
  do
    vmName=$(vm_running "*" "*" | grep ${vmIp}$ | cut -d ' ' -f 1)
    [ -n "${vmName}" ] && break
    sleep 1
    nameFindingIteration=$((${nameFindingIteration}+1))
  done
  [ ${nameFindingIteration} -gt ${nameFindingIterationMax} ] && return 1
  echo $vmName
}

vm_group() {
  local vmName=$1

  vm_running "*" "*" | grep ${vmName} | cut -d ' ' -f 2 | cut -d / -f 1
}

vm_type() {
  local vmName=$1

  vm_running "*" "*" | grep ${vmName} | cut -d ' ' -f 2 | cut -d / -f 2
}

vm_console_port() {
  local vmName=$1

  pgrep -f qemu-system-${vmSystemType} -a | grep ${vmName} | sed 's/^.*-monitor //;s/ .*$//' | cut -d, -f1 | cut -d: -f3
}

vm_spice_port() {
  local vmName=$1

  pgrep -f qemu-system-${vmSystemType} -a | grep ${vmName} | sed 's/^.*-spice port=//;s/,.*$//'
}

vm_group_destroy() {
  local groupName=$1

  local subGroupName="*"
  local vmName="*"
  rm ${vmBaseDir}/${groupName}/${subGroupName}/${vmName}/*
  rmdir ${vmBaseDir}/${groupName}/${subGroupName}/${vmName}
  rmdir ${vmBaseDir}/${groupName}/${subGroupName} 2>/dev/null
  rmdir ${vmBaseDir}/${groupName}/ 2>/dev/null
}
