#!/bin/bash

#    (c) 2016-2017, n0vember <n0vember@half-9.net>
#
#    This file is part of nocloud.
#
#    nocloud is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    nocloud is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with nocloud.  If not, see <http://www.gnu.org/licenses/>.

cd "$(dirname $0)/.."

. etc/nocloud_net.conf

iptables_rules() {
  if [ "$1" == "on" ] ; then
    insertRule="-I"
    appendRule="-A"
    newChain="-N"
  else
    insertRule="-D"
    appendRule="-D"
    newChain="-X"
  fi
  [ "$1" == "on" ] && iptables ${newChain} NOCLOUD
  iptables ${insertRule} INPUT -i ${bridgeInterface} -j ACCEPT
  iptables ${insertRule} FORWARD -j NOCLOUD
  iptables ${insertRule} FORWARD -o ${bridgeInterface} -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  iptables ${appendRule} NOCLOUD -i ${bridgeInterface} -j ACCEPT
  iptables -t nat ${appendRule} POSTROUTING -s ${bridgeNet} ! -o ${bridgeInterface} -j MASQUERADE
  [ "$1" != "on" ] && iptables ${newChain} NOCLOUD
}

if [ "$1" == "start" ] ; then
  ip link add name ${bridgeInterface} type bridge
  ip link set ${bridgeInterface} up
  ip addr add ${bridgeAddress} dev ${bridgeInterface}
  iptables_rules on
  sysctl -q net.ipv4.conf.all.forwarding=1
fi

if [ "$1" == "stop" ] ; then
  iptables_rules off
  ip link delete ${bridgeInterface}
fi
