#!/bin/bash

ko() { echo "$1 NOT FOUND."; }
ok() { echo "$1 found."; }
tst() {
  cmd=$1
  name=$2
  eval "${cmd}" >/dev/null 2>&1 && ok ${name} || ko ${name}
}

tst "which qemu-system-$(uname -m)" "qemu"
tst "which dnsmasq" "dnsmasq"
tst "which spicy" "spicy"

for oldFile in bin/vmrunning bin/vmcreate
do
  [ -f /usr/local/${oldFile} ] && rm /usr/local/${oldFile} || echo -n
done

echo "%kvm ALL=(ALL) NOPASSWD: /usr/local/sbin/vmnat" > /etc/sudoers.d/kvm-iptables
