#!/bin/bash

ko() { echo "$1 NOT FOUND."; }
ok() { echo "$1 found."; }
tst() {
  cmd=$1
  name=$2
  eval "${cmd}" >/dev/null 2>&1 && ok ${name} || ko ${name}
}

tst "which qemu-system-$(uname -m)" "qemu"
tst "which dnsmasq" "dnsmasq"
tst "which spicy" "spicy"
tst "which tree" "tree"

for oldFile in bin/vmrunning bin/vmcreate bin/vminstantiate bin/vmstop bin/vmconsole bin/vm
do
  [ -f /usr/local/${oldFile} ] && rm /usr/local/${oldFile} || echo -n
done

# Grant kvm group the right to set port translations
echo "%kvm ALL=(ALL) NOPASSWD: /usr/local/sbin/vmnat" > /etc/sudoers.d/kvm-iptables

# Check user
user_name=$(last $(tty | sed 's:/dev/::') | grep "logged in" | sed 's: .*::')
other_user_name=""
if [ "${user_name}" == root ] ; then
  echo installing as root...
  echo -n "do you want to set up an other user to use nocloud ? (yes/no)"
  read other_user
  case "${other_user}" in
    "y|yes")
      while $(grep "^${other_user_name}:" /etc/passwd)
      do
        echo -n "give te user's name : "
        read other_user_name
      done
      user_name=${other_user_name}
      ;;
    "*")
      echo "I don't think using root is a good idea, but OK"
      ;;
  esac
fi
echo "adding user ${user_name} in kvm group"
usermod -a -G kvm ${user_name}

exit

# initiate dhcp-hostsfile
touch /usr/local/etc/nocloud-dhcp-hostsfile
chmod 664 /usr/local/etc/nocloud-dhcp-hostsfile
chown root:kvm /usr/local/etc/nocloud-dhcp-hostsfile
