#!/bin/bash

cd "$(dirname $0)/.."

. etc/nocloud_net.conf

[ -d /etc/qemu ] || mkdir -p /etc/qemu
[ -f /etc/qemu/bridge.conf ] || echo "allow all" > /etc/qemu/bridge.conf
grep "^allow all$" /etc/qemu/bridge.conf >/dev/null || echo "allow all" >> /etc/qemu/bridge.conf
chown -R root:kvm /etc/qemu
chmod 750 /etc/qemu
chmod 640 /etc/qemu/bridge.conf
